name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Build & test
        run: ./gradlew clean build
      - name: Configure Gradle credentials
        run: |
          mkdir -p ~/.gradle
          {
            echo "mavenCentralUsername=$MAVEN_CENTRAL_USERNAME";
            echo "mavenCentralPassword=$MAVEN_CENTRAL_PASSWORD";
          } >> ~/.gradle/gradle.properties
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      - name: Publish to Maven Central (Portal)
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: ./gradlew publishAllPublicationsToMavenCentral --no-daemon --stacktrace
#        run: ./gradlew publishAllPublicationsToMavenCentral --no-daemon --stacktrace