name: tests (latest)

on:
  push:
    branches: ["**"]

jobs:
  test_latest:
    name: Unit tests (@Tag("latest"))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Run only @Tag("latest") tests
        run: ./gradlew test -x publish -Djunit.jupiter.tags.include=latest --no-daemon --stacktrace